#!/bin/bash

##
## i-doit virtual appliance
## Create issue files
##

##
## Copyright (C) 2018 synetics GmbH, <https://i-doit.com/>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
##

set -euo pipefail
IFS=$'\n\t'

if [ "$METHOD" = "loopback" ]; then
    exit 0
fi

# Only run from ifup:
if [ "$MODE" != "start" ]; then
    exit 0
fi

applianceVersion="$(cat /etc/appliance_version)"
ipAddress="$(ip route get 1 | awk '{print $NF;exit}')"

function copyIssue {
    local file="$1"

    cp /etc/issue-standard /etc/"$file"

    {
        echo "                              i-doit virtual appliance ${applianceVersion}"
        echo ""
        echo "                                            $ipAddress"
    } >> /etc/"$file"
}

copyIssue "issue"
copyIssue "issue.net"
